# not finished.
name: "Pack large mods to reduce repo size"

run-name: Link ${{ inputs.mods }} to ${{ output.repos }}

on: 
  push:
    branches:
      - main
    paths:
      - mods/**.jar

jobs:
  checkout:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            mods
            .github/workflows
  analyze:
    runs-on: self-hosted
    permissions: {}
    defaults:
      run:
        shell: bash
        working-directory: ./scripts
    steps:
      - name: Run Python Script
        run: |
          mod-linker.py
      - name: Cache mod_data
        uses: actions/cache@v4
        with:
          key: cache-mod-data-${{ hashFiles('**/mod_cache.json') }}
          path: |
            mods/mod_cache.json
